# text_extractor_pdf_ryder

# format_1

In [14]:
import os
import pandas as pd
import cv2
import camelot


f = []
v = []
v1 = []
m = []
x = []
y = []
z = []
s1=[]
s2=[]
s3=[]


input_dir = r'C:\Users\majidmm\Documents\AMXL\OUTPUT_FILES\files_dump_all_patterns\pattern_1\\'

for root, dirs, filenames in os.walk(input_dir):
    for filename in filenames:
            print(filename)
            f.append(filename)
            tables = camelot.read_pdf(input_dir + filename,pages='1,2',flavor='lattice')
            a=tables[0].df
            b=tables[1].df
            
            vehicle_number = a.iloc[25, 5].strip()
#             print(vehicle_number)
            v.append(vehicle_number)
    
            vehicle_number_2 = a.iloc[25, 4].strip()
#             print(vehicle_number)
            v2=vehicle_number_2.strip('Vehicle Number')
            vx=v2.strip()
            v1.append(vx)
            
            mileage_rate = a.iloc[17,1].strip()
            m.append(mileage_rate.strip('$'))
            
            mileage_units=a.iloc[17, 2]
#             print(mileage_units)
            x.append(mileage_units)
        
            pick_date = a.iloc[14, 4].strip()
            pick_date.strip('Pick Date/Time')
#             print(pick_date.strip('Pick Date/Time'))
            y.append(pick_date.strip('Pick Date/Time'))
            
            return_date = a.iloc[15, 4].strip()
            return_date.strip('Return Date/Time')
#             print(return_date.strip('Return Date/Time'))
            z.append(return_date.strip('Return Date/Time'))
            
            try:
                sales_tax1=b.iloc[0,1].strip()
                s1.append(sales_tax1)
            except IndexError:
                s1.append('')
            
            try:
                sales_tax2=b.iloc[1,1].strip()
                s2.append(sales_tax2)
            except IndexError:
                s2.append('')
            
            try:
                sales_tax3=b.iloc[2,1].strip()
                s3.append(sales_tax3)
            except IndexError:
                s3.append('')
            
            
            print('-='*20)
            
df = pd.DataFrame(list(zip(f, v, v1, x, y, z, m, s1, s2, s3)),columns=['file_Name','VIN Number x','VIN Number y','Claimed Miles','Rental Start date','Rental End date','Mileage Rate','s1','s2','s3'])
df['VIN Number']=df['VIN Number x']+df['VIN Number y']
df['s1']=df['s1'].str.strip('$')
df['s2']=df['s2'].str.strip('$')
df['s3']=df['s3'].str.strip('$')


df['Sales Tax']=df['s1']+df['s2']+df['s3']
# df.to_csv(r"C:\Users\majidmm\Documents\AMXL\OUTPUT_FILES\output_end\p1_end.csv",index=False,columns=('file_Name','VIN Number','Mileage Rate','Claimed Miles','Rental Start date','Rental End date','s1','s2'))
df

14431777_Rental_Communication.pdf
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
14431968_Rental_Communication.pdf
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
232557.pdf
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
238997.pdf
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
388809.pdf
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
5991468ryder.pdf
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
685175_0606_0613_mileage.pdf
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

,file_Name,VIN Number x,VIN Number y,Claimed Miles,Rental Start date,Rental End date,Mileage Rate,s1,s2,s3,VIN Number,Sales Tax
0,14431777_Rental_Communication.pdf,264893,,1640,06/10/2020 07:00 AM\n,06/17/2020 07:00 AM\n,.10,,44.70,,264893,44.70
1,14431968_Rental_Communication.pdf,233780,,867,06/11/2020 07:00 AM\n,06/18/2020 07:00 AM\n,.10,,36.97,,233780,36.97
2,232557.pdf,232557,,485,06/12/2020 07:00 AM\n,06/18/2020 11:59 PM\n,.10,24.74,,,232557,24.74
3,238997.pdf,238997,,1025,06/10/2020 07:00 AM\n,06/17/2020 06:59 AM\n,.10,28.32,,,238997,28.32
4,388809.pdf,388809,,1203,06/15/2020 07:00 AM\n,06/16/2020 02:48 PM\n,.10,12.12,,,388809,12.12
5,5991468ryder.pdf,810582,,1043,05/28/2020 07:00 AM\n,06/01/2020 06:59 AM\n,.10,23.13,,,810582,23.13
6,685175_0606_0613_mileage.pdf,685175,,930,06/06/2020 08:00 AM\n,06/13/2020 07:00 AM\n,.10,,26.32,,685175,26.32

# format_2

In [ ]:
import os
import pandas as pd
import cv2
import camelot


f = []
v = []
x = []
y = []
z = []

input_dir = r'C:\Users\majidmm\Documents\AMXL\OUTPUT_FILES\files_dump_all_patterns\pattern_2\\'

for root, dirs, filenames in os.walk(input_dir):
    for filename in filenames:
        try:
            print(filename)
            f.append(filename)
            tables = camelot.read_pdf(input_dir + filename,,pages='3',flavor='stream',split_text= True,edge_tol=500)
            a=tables[0].df
            
            vehicle_number = a.iloc[6, 2]
#             print(vehicle_number)
            v.append(vehicle_number)

            pick_date = a.iloc[10, 2]
#             print(pick_date.strip('Pick Date/Time'))
            x.append(pick_date.strip('Pick Date/Time'))

            return_date = a.iloc[11, 2]
#             print(return_date.strip('Return Date/Time'))
            y.append(return_date.strip('Return Date/Time'))

            mileage_units=a.iloc[20, 2]
#             print(mileage_units)
            z.append(mileage_units)

            period_billed = a.iloc[13, 2]
#             print(period_billed)
            w.append(period_billed)
            
        except:
            continue


df = pd.DataFrame(list(zip(f, v, x, y, z, w)),columns=['file_Name','VIN Number','Rental Start date','Rental End date','Claimed Miles','period_billed'])
df.to_csv(r"C:\Users\majidmm\Documents\AMXL\OUTPUT_FILES\output_end\p2_end.csv",index=False)

# format_3

In [12]:
from PIL import Image
import cv2 
import pytesseract
import re 
from pytesseract import Output
import pandas as pd
import os


tesseract_exe_path_installation="C:\\Users\\majidmm\\AppData\\Local\\Tesseract-OCR\\tesseract.exe"
pytesseract.pytesseract.tesseract_cmd=tesseract_exe_path_installation



f = []
v = []
m = []
x = []
y = []
z = []
s1 = []
s2 = []
s3 = []

input_dir = r'C:\Users\majidmm\Documents\AMXL\OUTPUT_FILES\files_dump_all_patterns\pattern_3\\'

for root, dirs, filenames in os.walk(input_dir):
    for filename in filenames:
        try:
            print(filename)
            f.append(filename.rstrip('.png')+'.pdf')
            img = cv2.imread(input_dir+filename)
            custom_config = r' --psm 6'
            text = pytesseract.image_to_string(img,output_type=Output.STRING,config=custom_config)
            t=text.lower()
            
            left = 'hicle no:'
            right = 'customer information'
            vehicle_number = t[t.index(left)+len(left):t.index(right)]
            vehicle_number.strip(',')
            vehicle_number.strip(':')
#             print(vehicle_number)
            v.append(vehicle_number[0:7].strip())
            
            left = 'mileage rate'
            right = '/m ='
            mileage_rate = t[t.index(left)+len(left):t.index(right)]
            m.append(mileage_rate[-6:])
        
            
            left = 'out:'
            right = 'used:'
            pick_date = t[t.index(left)+len(left):t.index(right)]
#             print(pick_date[0:15])
            x.append(pick_date[0:10].strip())
            
            left = 'in:'
            right = 'st:'
            return_date = t[t.index(left)+len(left):t.index(right)]
#             print(return_date[0:15])
            y.append(return_date[0:10].strip())
            
            left = 'mileage rate'
            right = 'miles'
            mileage = t[t.index(left)+len(left):t.index(right)]
#             print(mileage)
            z.append(mileage.strip())
    
#             left = 'sales tax'
#             right = 'special tax'
#             sales_tax = t[t.index(left)+len(left):t.index(right)]
# #             print(sales_tax[-6:].strip())
#             s1.append(sales_tax[-6:].strip())
            
#             left = 'special tax =s'
#             right = '** special rate'
#             special_tax = t[t.index(left)+len(left):t.index(right)]
# #             print(special_tax.strip())
#             s2.append(special_tax.strip())

#             left = '1 week'
#             right = '** special rate'
#             week_tax = t[t.index(left)+len(left):t.index(right)]
# #             print(week_tax[-5:0].strip())
#             s3.append(week_tax[-5:0].strip())
            
        except:
            continue


df = pd.DataFrame(list(zip(f, v, z, x, y, m)),columns=['file_Name','VIN Number','Claimed Miles','Rental Start date','Rental End date','Mileage Rate'])
df['Claimed Miles']=df['Claimed Miles'].replace('o','0')
df.to_csv(r"C:\Users\majidmm\Documents\AMXL\OUTPUT_FILES\output_end\p3_end.csv",index=False,columns=('file_Name','VIN Number','Mileage Rate','Claimed Miles','Rental Start date','Rental End date'))
df

229593.png
232267___june_18.png
246006___June_22.png
246194___june_17.png
248017___june_18.png
248105.png
248106.png
249214___june_17.png
249232___june_18.png
259056___june_17.png
264632___June_23.png
264808___june_17.png
337498.png
68.26.png
683969.png
685254.png
6_17_20_Truck_643607.png
870230.png
RYDERINVOICE0601.png

,file_Name,VIN Number,Claimed Miles,Rental Start date,Rental End date,Mileage Rate
0,229593.pdf,229593,957,06/15/20,06/22/20,0.1000
1,232267___june_18.pdf,232267,794,06/11/20,06/18/20,0.1000
2,246006___June_22.pdf,246006,1250,06/15/20,06/22/20,0.1000
3,246194___june_17.pdf,246194,1035,06/10/20,06/17/20,0.1000
4,248017___june_18.pdf,248017,465,06/15/20,06/18/20,0.1000
5,248105.pdf,248105,662,06/12/20,06/19/20,0.1000
6,248106.pdf,248106,2045,06/15/20,06/22/20,0.1000
7,249214___june_17.pdf,249214,1073,06/10/20,06/17/20,0.1000
8,249232___june_18.pdf,249232,1314,06/11/20,06/18/20,0.1000
9,259056___june_17.pdf,259056,1855,06/10/20,06/17/20,0.1000
10,264632___June_23.pdf,264632,1590,06/16/20,06/23/20,0.1000
11,264808___june_17.pdf,264808,1021,06/10/20,06/17/20,0.1000
12,337498.pdf,337498,1026,06/15/20,06/22/20,0.1000
13,68.26.pdf,744301,0,06/03/20,06/04/20,0.1000
14,683969.pdf,683969,1170,06/16/20,06/23/20,0.1000
15,685254.pdf,685254,391,06/12/20,06/19/20,0.1000
16,6_17_20_Truck_643607.pdf,643607,1577,06/10/20,06/17/20,0.1000
17,870230.pdf,870230,171,06/15/20,06/22/20,0.1000
18,RYDERINVOICE0601.pdf,810582,877,06/01/20,06/03/20,0.1000

# format_4

In [ ]:
import os
import pandas as pd
import cv2
import camelot


f = []
v = []
m = []
x = []
y = []
z = []

input_dir = r'C:\Users\majidmm\Documents\AMXL\OUTPUT_FILES\files_dump_all_patterns\pattern_4\\'

for root, dirs, filenames in os.walk(input_dir):
    for filename in filenames:
        try:
            print(filename)
            f.append(filename)
            tables = camelot.read_pdf(input_dir + filename,flavor='stream')
            a=tables[0].df
            
            vehicle_number = a.iloc[1, 1].strip()
#             print(vehicle_number)
            v.append(vehicle_number)
    
                    
            mileage_rate = a.iloc[8, 5].strip()
            m.append(mileage_rate.strip('$'))
            
            mileage_units=a.iloc[10, 1]
#             print(mileage_units)
            x.append(mileage_units)
        
            pick_date = a.iloc[6, 1].strip()
            pick_date.strip('Pick Date/Time')
#             print(pick_date.strip('Pick Date/Time'))
            y.append(pick_date.strip('Pick Date/Time'))
            
            return_date = a.iloc[7, 1].strip()
            return_date.strip('Return Date/Time')
#             print(return_date.strip('Return Date/Time'))
            z.append(return_date.strip('Return Date/Time'))
            
            print('-='*20)
            
        except:
            continue


df = pd.DataFrame(list(zip(f, v, x, y, z, m)),columns=['file_Name','VIN Number','Claimed Miles','Rental Start date','Rental End date','Mileage Rate'])
df.to_csv(r"C:\Users\majidmm\Documents\AMXL\OUTPUT_FILES\output_end\p4_end.csv",index=False,columns=('file_Name','VIN Number','Mileage Rate','Claimed Miles','Rental Start date','Rental End date'))